<?php

// $agencies = [
// 	'fantastical' = 'http://thefantastical.com/jobs/',
// 	'viewpoint' = 'http://www.viewpointcreative.com/jobs',
// 	'adrenaline' = 'http://adrenalineshot.com/contact-us/',
// 	'allengerritsen' = 'http://www.a-g.com/careers/',
// 	'Almighty' = 'http://www.bealmighty.com/careers/',
// 	'altr' = '',
// 	'AMP'  = 'http://ampagency.com/about/careers',
// 	'GYKAntler' = '',
// 	'Argus' = '',
// 	'Arnold' = 'http://arn.com/careers/',
// 	'BEAM' = 'http://www.beamland.com/jobs.php',
// 	'BermanCreative' = 'http://www.bermanadvertising.com/careers',
// 	'Blackmath' = '',
// 	'BrandContent' = '',
// 	'CaptainsofIndustry' = '',
// 	'CaratInteractive' = '',
// 	'ConnellyPartners' = '',
// 	'HavasWorldwide' = '',
// 	'FORGEWorldwide' = '',
// 	'FullContactAdvertising' = '',
// 	'GenuineInteractive' = '',
// 	'GeorgePJohnson' = '',
// 	'HillHolliday' = '',
// 	'HollandMark' = '',
// 	'L7' = '',
// 	'Libretto' = '',
// 	'MMB' = '',
// 	'Mullen' = '',
// 	'PARTNERSSimons' = '',
// 	'SapientNitro' = '',
// 	'SmallArmy' = '',
// 	'Studiocom' = ''
// ];
